import type { DataResponse } from "../types/internship";

export const MOCK_DATA: DataResponse = {
  items: [
    {
      openingId: 1038,
      sessionId: 4,
      company: {
        companyId: 122,
        companyNameTh: "บริษัท บี.กริม เพาเวอร์ จำกัด (มหาชน)",
        companyNameEn: "B.Grimm Power Public Company Limited",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/4653c14b-0584-484c-a768-7d9258d16b94?v=1739777296831",
        website: "https://www.bgrimmpower.com/en/home",
        facebook: "https://www.facebook.com/B.GrimmPeopleandCareer",
        line: "",
      },
      title: "นักศึกษาฝึกงาน (Digital Transformation)",
      description:
        "<p><strong>Location:</strong> Head Office, Krungthep Kreetha, Huamark, Bangkapi 10240</p>...",
      quota: 1,
      openForCooperativeInternship: false,
      compensationAmount: 350,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "On-Site",
      requirements: "<p><br></p>",
      tags: [
        { tagId: 2, tagName: "UX/UI" },
        { tagId: 32, tagName: "infrastructure" },
        { tagId: 41, tagName: "Developer" },
        { tagId: 53, tagName: "Data Engineer" },
        { tagId: 264, tagName: "Data Scientist" },
        { tagId: 361, tagName: "Network" },
        { tagId: 366, tagName: "Security" },
        { tagId: 367, tagName: "Security Policy" },
      ],
      officeName: "Head Office, Krungthep Kreetha",
      officeAddressLine1: "อาคาร Dr. Gerhard Link Building...",
      officeAddressLine2: "รถไฟฟ้าสายสีเหลือง...",
      recruitmentContactChannel:
        "https://www.facebook.com/B.GrimmPeopleandCareer",
      openingDetailContactChannel:
        "https://www.facebook.com/B.GrimmPeopleandCareer",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 2,
      isBookmarked: false,
    },
    {
      openingId: 1040,
      sessionId: 4,
      company: {
        companyId: 56,
        companyNameTh: "บริษัท อโยเดีย จำกัด",
        companyNameEn: "Ayodia",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/938e1f91-db07-4d86-b056-28ee0b3ac588?v=1698291995001",
        website: "https://ayodiacompany.com",
        facebook: "https://www.facebook.com/AyodiaCompany",
        line: "",
      },
      title: "Programmer",
      description: "...",
      quota: 4,
      openForCooperativeInternship: false,
      compensationAmount: 200,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "On-Site",
      requirements: "...",
      tags: [
        {
          tagId: 284,
          tagName: "Angular, ASP.NET Web API และ Entity Framework",
        },
      ],
      officeName: "สำนักงานใหญ่",
      officeAddressLine1: "เลขที่ 21/11 ถนน กรุงธนบุรี...",
      officeAddressLine2: "BTS สถานีวงเวียนใหญ่ ทางออก 1",
      recruitmentContactChannel: "คุณจิราภรณ์ apply-now@ayodiacompany.com",
      openingDetailContactChannel: "คุณจิราภรณ์ apply-now@ayodiacompany.com",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 2,
      isBookmarked: false,
    },
    {
      openingId: 1041,
      sessionId: 4,
      company: {
        companyId: 56,
        companyNameTh: "บริษัท อโยเดีย จำกัด",
        companyNameEn: "Ayodia",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/938e1f91-db07-4d86-b056-28ee0b3ac588?v=1698291995001",
        website: "https://ayodiacompany.com",
        facebook: "https://www.facebook.com/AyodiaCompany",
        line: "",
      },
      title: "Software Tester",
      description: "...",
      quota: 2,
      openForCooperativeInternship: false,
      compensationAmount: 200,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "On-Site",
      requirements: "...",
      tags: [{ tagId: 285, tagName: "Automated Test Tools " }],
      officeName: "สำนักงานใหญ่",
      officeAddressLine1: "เลขที่ 21/11 ถนน กรุงธนบุรี...",
      officeAddressLine2: "ออฟฟิศอยู่ติด BTS วงเวียนใหญ่ ทางออก 1",
      recruitmentContactChannel: "...",
      openingDetailContactChannel: "...",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 2,
      isBookmarked: false,
    },
    {
      openingId: 1042,
      sessionId: 4,
      company: {
        companyId: 56,
        companyNameTh: "บริษัท อโยเดีย จำกัด",
        companyNameEn: "Ayodia",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/938e1f91-db07-4d86-b056-28ee0b3ac588?v=1698291995001",
        website: "https://ayodiacompany.com",
        facebook: "https://www.facebook.com/AyodiaCompany",
        line: "",
      },
      title: "Business Analyst",
      description: "...",
      quota: 2,
      openForCooperativeInternship: false,
      compensationAmount: 200,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "On-Site",
      requirements: "...",
      tags: [],
      officeName: "สำนักงานใหญ่",
      officeAddressLine1: "เลขที่ 21/11 ถนน กรุงธนบุรี...",
      officeAddressLine2: "อยู่ติด BTS วงเวียนใหญ่ ทางออก 1",
      recruitmentContactChannel: "...",
      openingDetailContactChannel: "...",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 1,
      isBookmarked: false,
    },
    {
      openingId: 1047,
      sessionId: 4,
      company: {
        companyId: 42,
        companyNameTh: "บริษัท ดีมีเตอร์ ไอซีที จำกัด",
        companyNameEn: "Demeter ICT",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/0f45a453-1dad-4cd3-b6ff-c80761b24119?v=1701072977024",
        website: "https://www.dmit.co.th/en/homepage/",
        facebook: "https://www.facebook.com/demeterict",
        line: "hr.dmit",
      },
      title: "Product QA",
      description: "...",
      quota: 1,
      openForCooperativeInternship: false,
      compensationAmount: 300,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "Hybrid",
      requirements: null,
      tags: [
        { tagId: 2, tagName: "UX/UI" },
        { tagId: 41, tagName: "Developer" },
      ],
      officeName: "สำนักงานใหญ่",
      officeAddressLine1: "อาคาร Thai CC Tower...",
      officeAddressLine2: "",
      recruitmentContactChannel: "boonyarin.p@dmit.co.th",
      openingDetailContactChannel: "ID.hrdmit",
      startDate: "2026-01-04T17:00:00.000Z",
      endDate: "2026-04-29T17:00:00.000Z",
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 3,
      isBookmarked: false,
    },
    {
      openingId: 1048,
      sessionId: 4,
      company: {
        companyId: 2,
        companyNameTh: "ธนาคารแห่งประเทศไทย",
        companyNameEn: "BOT",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/e8497e52-c48d-493c-8680-829576e53205?v=1698655944847",
        website: "https://www.bot.or.th/th/about-us/recruitment.html",
        facebook: "https://www.facebook.com/Career.BankofThailand",
        line: "",
      },
      title: "System Analyst (IT)",
      description: "...",
      quota: 1,
      openForCooperativeInternship: false,
      compensationAmount: 450,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "On-Site",
      requirements: null,
      tags: [],
      officeName: "ธนาคารแห่งประเทศไทย สำนักงานใหญ่",
      officeAddressLine1: "เลขที่ 273 ถนน สามเสน...",
      officeAddressLine2: "",
      recruitmentContactChannel: "...",
      openingDetailContactChannel: "...",
      startDate: "2026-05-31T17:00:00.000Z",
      endDate: "2026-07-30T17:00:00.000Z",
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 4,
      isBookmarked: false,
    },
    {
      openingId: 1058,
      sessionId: 4,
      company: {
        companyId: 150,
        companyNameTh: "บริษัท ช็อคโก้ คาร์ด เอ็นเตอร์ไพรส์ จำกัด (ChocoCRM)",
        companyNameEn: "CHOCO CARD ENTERPRISE Co., Ltd.",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/074e2844-51b4-4f3f-99b1-cc81e44ccf27?v=1761047535641",
        website: "https://chococrm.com/",
        facebook: "https://www.facebook.com/chococrmofficial",
        line: "",
      },
      title: "Backend Developer",
      description: "...",
      quota: 2,
      openForCooperativeInternship: false,
      compensationAmount: 200,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "Hybrid",
      requirements: "...",
      tags: [
        { tagId: 7, tagName: "C#" },
        { tagId: 29, tagName: "SQL" },
        { tagId: 41, tagName: "Developer" },
        { tagId: 52, tagName: ".Net Core" },
        { tagId: 58, tagName: "web application" },
        { tagId: 126, tagName: "Web Developer" },
        { tagId: 208, tagName: "Backend " },
      ],
      officeName: "บริษัท ช็อคโก้ คาร์ด เอ็นเตอร์ไพรส์ จำกัด",
      officeAddressLine1: "เลขที่ 2150/4 ถนน สุขุมวิท...",
      officeAddressLine2: "สามารถเดินจากรถไฟฟ้า BTS บางจาก...",
      recruitmentContactChannel: "hr@chococrm.com",
      openingDetailContactChannel: "hr@chococrm.com",
      startDate: "2026-04-30T17:00:00.000Z",
      endDate: "2026-07-30T17:00:00.000Z",
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 1,
      isBookmarked: false,
    },
    {
      openingId: 1065,
      sessionId: 4,
      company: {
        companyId: 11,
        companyNameTh: "บริษัท บลูบิค กรุ๊ป จำกัด (มหาชน)",
        companyNameEn: "Bluebik",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/a0fab6bb-2c58-4c4a-9914-1194c4a6f5d5?v=1699932423277",
        website: "https://bluebik.com/",
        facebook: "https://www.facebook.com/bluebikgroup",
        line: "",
      },
      title: "Backend Engineer",
      description: "...",
      quota: 1,
      openForCooperativeInternship: false,
      compensationAmount: 300,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "Hybrid",
      requirements: "...",
      tags: [],
      officeName: "Bluebik Group",
      officeAddressLine1: "อาคาร อาคารเอ็มไพร์ทาวเวอร์...",
      officeAddressLine2: "BTS (ช่องนนทรี)",
      recruitmentContactChannel: "",
      openingDetailContactChannel: "",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 1,
      isBookmarked: true,
    },
    {
      openingId: 1070,
      sessionId: 4,
      company: {
        companyId: 114,
        companyNameTh: "บริษัท โกไฟว์ จำกัด",
        companyNameEn: "gofive",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/2bd29582-0e91-4255-9b17-64ab0d6ff00e?v=1734247862970",
        website: "https://www.gofive.co.th",
        facebook: "https://tr.ee/HJ0sTKLVqr",
        line: "https://tr.ee/HQ52THm4rA",
      },
      title: "Internship Developer",
      description: "...",
      quota: 3,
      openForCooperativeInternship: false,
      compensationAmount: 200,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "On-Site",
      requirements: null,
      tags: [
        { tagId: 7, tagName: "C#" },
        { tagId: 41, tagName: "Developer" },
        { tagId: 52, tagName: ".Net Core" },
        { tagId: 70, tagName: "FullStack" },
        { tagId: 86, tagName: "AI" },
        { tagId: 407, tagName: "SAAS" },
      ],
      officeName: "สาขา FYI Center (พระรามที่ 4) ",
      officeAddressLine1: "อาคาร FYI Center...",
      officeAddressLine2: "",
      recruitmentContactChannel: "https://jobs.empeo.com/Gofive/102469",
      openingDetailContactChannel: "...",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 5,
      isBookmarked: true,
    },
    {
      openingId: 1073,
      sessionId: 4,
      company: {
        companyId: 114,
        companyNameTh: "บริษัท โกไฟว์ จำกัด",
        companyNameEn: "gofive",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/2bd29582-0e91-4255-9b17-64ab0d6ff00e?v=1734247862970",
        website: "https://www.gofive.co.th",
        facebook: "https://tr.ee/HJ0sTKLVqr",
        line: "https://tr.ee/HQ52THm4rA",
      },
      title: "Internship Automate Tester",
      description: "...",
      quota: 3,
      openForCooperativeInternship: false,
      compensationAmount: 200,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "Work From Home",
      requirements: null,
      tags: [
        { tagId: 64, tagName: "automated testing" },
        { tagId: 280, tagName: "playwright" },
        { tagId: 408, tagName: "Postman" },
        { tagId: 409, tagName: "JMeter" },
      ],
      officeName: "สาขา FYI Center (พระรามที่ 4) ",
      officeAddressLine1: "อาคาร FYI Center...",
      officeAddressLine2: "",
      recruitmentContactChannel: "...",
      openingDetailContactChannel: "...",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 1,
      isBookmarked: false,
    },
    {
      openingId: 1074,
      sessionId: 4,
      company: {
        companyId: 114,
        companyNameTh: "บริษัท โกไฟว์ จำกัด",
        companyNameEn: "gofive",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/2bd29582-0e91-4255-9b17-64ab0d6ff00e?v=1734247862970",
        website: "https://www.gofive.co.th",
        facebook: "https://tr.ee/HJ0sTKLVqr",
        line: "https://tr.ee/HQ52THm4rA",
      },
      title: "Internship Flutter Mobile Developer",
      description: "...",
      quota: 2,
      openForCooperativeInternship: false,
      compensationAmount: null,
      compensationType: null,
      workingCondition: null,
      requirements: null,
      tags: [],
      officeName: "สาขา FYI Center (พระรามที่ 4) ",
      officeAddressLine1: "อาคาร FYI Center...",
      officeAddressLine2: "",
      recruitmentContactChannel: "...",
      openingDetailContactChannel: "...",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 2,
      isBookmarked: false,
    },
    {
      openingId: 1078,
      sessionId: 4,
      company: {
        companyId: 46,
        companyNameTh: "บริษัท ดีเวอร์ฮูด เอชที จำกัด",
        companyNameEn: "Deverhood HT",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/6fa37b52-9f4d-4285-abd1-7588a1b4e797?v=1698300961776",
        website: "http://www.Deverhood.com",
        facebook: "https://www.facebook.com/deverhood",
        line: "@Deverhood",
      },
      title: "Junior Developer (Trainee)",
      description: "...",
      quota: 2,
      openForCooperativeInternship: false,
      compensationAmount: 300,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "Hybrid",
      requirements: "...",
      tags: [
        { tagId: 12, tagName: "JavaScript" },
        { tagId: 29, tagName: "SQL" },
        { tagId: 70, tagName: "FullStack" },
        { tagId: 73, tagName: "Python" },
        { tagId: 155, tagName: "Medical" },
        { tagId: 156, tagName: "Education" },
      ],
      officeName: "สำนักงานใหญ่",
      officeAddressLine1: "990 อาคาร อัลดุลราฮิม เพลส...",
      officeAddressLine2: "...",
      recruitmentContactChannel: "...",
      openingDetailContactChannel: "...",
      startDate: "2026-04-30T17:00:00.000Z",
      endDate: "2026-07-30T17:00:00.000Z",
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 3,
      isBookmarked: false,
    },
    {
      openingId: 1091,
      sessionId: 4,
      company: {
        companyId: 41,
        companyNameTh: "บริษัท อินเทลชั่น จำกัด",
        companyNameEn: "Inteltion",
        logoUrl:
          "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/8fe16fec-acd7-4e56-becc-0636366e3408?v=1699592379528",
        website: "https://www.inteltion.com/",
        facebook: "https://www.facebook.com/inteltion?locale=th_TH",
        line: "sophanatl.",
      },
      title: "Data Engineer",
      description: "...",
      quota: 1,
      openForCooperativeInternship: false,
      compensationAmount: 400,
      compensationType: {
        compensationTypeId: 1,
        compensationType: "บาท/วัน",
      },
      workingCondition: "Hybrid",
      requirements: null,
      tags: [
        { tagId: 20, tagName: "Consultant" },
        { tagId: 29, tagName: "SQL" },
        { tagId: 33, tagName: "AWS" },
        { tagId: 35, tagName: "ETL" },
        { tagId: 53, tagName: "Data Engineer" },
        { tagId: 73, tagName: "Python" },
        { tagId: 74, tagName: "Airflow" },
        { tagId: 121, tagName: "PySpark" },
        { tagId: 184, tagName: "Pandas" },
      ],
      officeName: "สำนักงานใหญ่",
      officeAddressLine1: "อาคาร พหลโยธินเพลส...",
      officeAddressLine2: "...",
      recruitmentContactChannel: "",
      openingDetailContactChannel: "",
      startDate: null,
      endDate: null,
      isPublished: true,
      isAcceptingApplication: true,
      inStudentDraftCount: 1,
      isBookmarked: false,
    },
  ],
  meta: {
    totalItem: 98,
    itemCount: 20,
    itemsPerPage: 20,
    totalPage: 5,
    currentPage: 1,
  },
};
